USE BookStoreDB

CREATE TABLE EMPLOYEE
(
	EmployeeID NVARCHAR(10) PRIMARY KEY,
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	Cellphone NVARCHAR(10) NOT NULL,
	EAddress NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) UNIQUE NOT NULL,
	Account NVARCHAR(50) UNIQUE NOT NULL,
	Passward NVARCHAR(50) NOT NULL,
	Office NVARCHAR(30) NOT NULL
)

CREATE TABLE CUSTOMER
(
	CustomerID NVARCHAR(10) PRIMARY KEY,
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	Sex BIT NOT NULL,
	Cellphone NVARCHAR(10) NOT NULL,
	CAddress NVARCHAR(50),
	Email NVARCHAR(50) UNIQUE,
	Account NVARCHAR(50) UNIQUE NOT NULL,
	Passward NVARCHAR(50) NOT NULL
)

CREATE TABLE PUBLISHER
(
	PublisherID NVARCHAR(6) PRIMARY KEY,
	PName NVARCHAR(20) NOT NULL,
	Phone NVARCHAR(10) NOT NULL,
	PAddress NVARCHAR(50) NOT NULL
)

CREATE TABLE CATEGORY
(
	CategoryID NVARCHAR(3) PRIMARY KEY,
	CType NVARCHAR(20) UNIQUE NOT NULL
) 

CREATE TABLE BOOK 
(
	ISBN NVARCHAR(13) PRIMARY KEY,
    BName NVARCHAR(50) NOT NULL,
	UnitPrice INT CHECK(UnitPrice >= 0) DEFAULT(0) NOT NULL,
	Quantity INT CHECK(Quantity >=0) DEFAULT(0) NOT NULL,
	Author NVARCHAR(50) NOT NULL,
	CategoryID NVARCHAR(3) FOREIGN KEY REFERENCES CATEGORY(CategoryID),
	PublisherID NVARCHAR(6) FOREIGN KEY REFERENCES PUBLISHER(PublisherID) ON UPDATE CASCADE,
	PublishDate DATETIME CHECK(PublishDate <= GETDATE()) DEFAULT(GETDATE()) NOT NULL,
	BDescription NVARCHAR(300),
	Cover NVARCHAR(100)
)

CREATE TABLE ORDERS
(
	OrderID NVARCHAR(15) PRIMARY KEY,
	OwnerID NVARCHAR(10) FOREIGN KEY REFERENCES CUSTOMER(CustomerID) NOT NULL,
	CreditCard NVARCHAR(16),
	PurchaseDate DATETIME DEFAULT(GETDATE()) NOT NULL,
	Phone NVARCHAR(10) NOT NULL,
	OAddress NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50), 
)

CREATE TABLE SHOP_CAR
(
	CustomerID NVARCHAR(10) FOREIGN KEY REFERENCES CUSTOMER(CustomerID),
	ISBN NVARCHAR(13) FOREIGN KEY REFERENCES BOOK(ISBN),
	Amount INT CHECK(Amount >=1) DEFAULT(1) NOT NULL,
	PRIMARY KEY(CustomerID, ISBN) 
)

CREATE TABLE CONTAIN
(
	OrderID NVARCHAR(15) FOREIGN KEY REFERENCES ORDERS(OrderID),
	ISBN NVARCHAR(13) FOREIGN KEY REFERENCES BOOK(ISBN),
	Quantity INT CHECK(Quantity >=1) DEFAULT (1) NOT NULL,
	PRIMARY KEY(OrderID, ISBN)
)

CREATE TABLE MANAGE
(
	EmployeeID NVARCHAR(10) FOREIGN KEY REFERENCES EMPLOYEE(EmployeeID),
	ISBN NVARCHAR(13) FOREIGN KEY REFERENCES BOOK(ISBN),
	Quantity INT CHECK(Quantity >=0) NOT NULL,
	ActionState NVARCHAR(10) NOT NULL,
	ManageDate DATETIME DEFAULT(GETDATE()) NOT NULL,
	PRIMARY KEY(EmployeeID, ISBN, ManageDate)
)

CREATE TABLE INTRESTING
(
	CustomerID NVARCHAR(10) FOREIGN KEY REFERENCES CUSTOMER(CustomerID),
	ISBN NVARCHAR(13) FOREIGN KEY REFERENCES BOOK(ISBN),
	AddDate DATETIME DEFAULT(GETDATE()) NOT NULL,
	PRIMARY KEY(CustomerID, ISBN)
)

